# Generated by Django 5.2.10 on 2026-01-11 20:48

import apps.core.schema
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('members', wagtail.fields.StreamField([('member', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nome', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Ruolo', 'max_length': 100}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Biografia', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('image', 2), ('bio', 3)]], {})}, verbose_name='Membri')),
            ],
            options={
                'verbose_name': 'Consiglio Direttivo',
                'verbose_name_plural': 'Consiglio Direttivo',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('address', models.CharField(blank=True, help_text='Indirizzo completo per la mappa', max_length=500, verbose_name='Indirizzo')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudine')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitudine')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('show_contact_form', models.BooleanField(default=True, verbose_name='Mostra form contatto')),
                ('form_success_message', models.CharField(default='Grazie per averci contattato!', max_length=255, verbose_name='Messaggio successo form')),
            ],
            options={
                'verbose_name': 'Contatti',
                'verbose_name_plural': 'Contatti',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventsArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Archivio Eventi',
                'verbose_name_plural': 'Archivio Eventi',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Eventi',
                'verbose_name_plural': 'Eventi',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Testo introduttivo per la pagina timeline', verbose_name='Introduzione')),
                ('articles', wagtail.fields.StreamField([('article', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo dell'articolo", 'label': 'Titolo', 'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine', 'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'label': 'Data pubblicazione'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Categoria o tema dell'articolo", 'label': 'Categoria', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Sommario', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Link approfondimento', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('image', 1), ('date_published', 2), ('article_section', 3), ('summary', 4), ('url', 5)]], {})}, verbose_name='Articoli')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TransparencyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('documents', wagtail.fields.StreamField([('document', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo', 'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Documento'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Descrizione', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('description', 2)]], {})}, verbose_name='Documenti')),
            ],
            options={
                'verbose_name': 'Trasparenza',
                'verbose_name_plural': 'Trasparenza',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Contenuto')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine')),
            ],
            options={
                'verbose_name': 'Chi Siamo',
                'verbose_name_plural': 'Chi Siamo',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_name', models.CharField(max_length=255, verbose_name='Nome evento')),
                ('start_date', models.DateTimeField(verbose_name='Data inizio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data fine')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nome luogo')),
                ('location_address', models.CharField(blank=True, max_length=500, verbose_name='Indirizzo luogo')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='Latitudine')),
                ('location_lon', models.FloatField(blank=True, null=True, verbose_name='Longitudine')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione')),
                ('event_status', models.CharField(choices=[('EventScheduled', 'Programmato'), ('EventCancelled', 'Annullato'), ('EventPostponed', 'Posticipato'), ('EventRescheduled', 'Riprogrammato')], default='EventScheduled', max_length=20, verbose_name='Stato evento')),
                ('gallery', wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Didascalia', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {})}, verbose_name='Galleria immagini')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('organization_name', models.CharField(default='MC Castellazzo', max_length=255, verbose_name='Nome organizzazione')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrizione')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(default='Torino', max_length=100, verbose_name='Città')),
                ('region', models.CharField(default='Piedmont', max_length=100, verbose_name='Regione')),
                ('country', models.CharField(default='IT', max_length=2, verbose_name='Paese')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Data fondazione')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Titolo hero')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sottotitolo hero')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine hero')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
    ]
