# Generated by Django 5.2.10 on 2026-01-14 20:11

import apps.core.schema
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0003_add_blocks_streamfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Contenuto')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
            bases=(apps.core.schema.SchemaOrgMixin, 'wagtailcore.page'),
        ),
    ]
