# Generated by Django 5.2.10 on 2026-01-14 20:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_privacypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='founding_year',
            field=models.PositiveIntegerField(default=1933, verbose_name='Anno di fondazione'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text="Sottotitolo nell'hero section", max_length=200, verbose_name='Sottotitolo Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, help_text="Titolo principale nell'hero section", max_length=100, verbose_name='Titolo Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='members_count',
            field=models.PositiveIntegerField(default=250, verbose_name='Numero soci attivi'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='timeline',
            field=wagtail.fields.StreamField([('timeline', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'La Nostra Storia', 'label': 'Titolo sezione', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Anno', 'max_length': 10}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo', 'max_length': 100}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Descrizione'}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Evidenzia (bordo gold)', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('navy', 'Navy'), ('amaranth', 'Amaranto')], 'label': 'Colore badge'}), 6: ('wagtail.blocks.StructBlock', [[('year', 1), ('title', 2), ('description', 3), ('highlight', 4), ('color', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Eventi', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('events', 7)]], {})}, verbose_name='Timeline Storica'),
        ),
    ]
