# Generated by Django 5.2.10 on 2026-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_add_about_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='cta_description',
            field=models.CharField(blank=True, help_text="Es: 'Dal 1933 accogliamo appassionati di moto...'", max_length=255, verbose_name='Descrizione CTA'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='cta_title',
            field=models.CharField(blank=True, help_text="Es: 'Pronto a Unirti a Noi?'", max_length=100, verbose_name='Titolo CTA'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='directions_car',
            field=models.CharField(blank=True, help_text="Es: 'Uscita A26 Alessandria Sud, 15 min'", max_length=150, verbose_name='Indicazioni auto'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='directions_parking',
            field=models.CharField(blank=True, help_text="Es: 'Ampio parcheggio gratuito disponibile'", max_length=150, verbose_name='Indicazioni parcheggio'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='directions_train',
            field=models.CharField(blank=True, help_text="Es: 'Stazione Alessandria + bus linea 5'", max_length=150, verbose_name='Indicazioni treno'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_note',
            field=models.CharField(blank=True, help_text="Es: 'Rispondiamo entro 24h'", max_length=100, verbose_name='Nota email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_description',
            field=models.CharField(blank=True, help_text="Testo sotto il titolo 'Dove Trovarci'", max_length=255, verbose_name='Descrizione mappa'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='opening_hours',
            field=models.TextField(blank=True, help_text="Un orario per riga, formato: 'Giorno: HH:MM - HH:MM'", verbose_name='Orari apertura'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='opening_hours_note',
            field=models.CharField(blank=True, help_text="Es: 'Serata sociale settimanale'", max_length=100, verbose_name='Nota orari'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_note',
            field=models.CharField(blank=True, help_text="Es: 'Chiamaci il giovedì sera'", max_length=100, verbose_name='Nota telefono'),
        ),
    ]
