# Generated by Django 5.2.10 on 2026-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_add_contact_page_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='organization_alternate_name',
            field=models.CharField(blank=True, default='Moto Club Castellazzo Bormida', help_text='Nome esteso o alternativo', max_length=150, verbose_name='Nome Alternativo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_city',
            field=models.CharField(default='Castellazzo Bormida', max_length=100, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_country',
            field=models.CharField(default='IT', help_text='Codice ISO 2 lettere (es. IT, FR, DE)', max_length=2, verbose_name='Paese'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_description',
            field=models.TextField(blank=True, default='Moto Club fondato nel 1933, affiliato FMI', help_text='Breve descrizione per Schema.org', verbose_name='Descrizione Organizzazione'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_founding_year',
            field=models.PositiveIntegerField(blank=True, default=1933, null=True, verbose_name='Anno Fondazione'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_name',
            field=models.CharField(default='MC Castellazzo Bormida', help_text="Nome ufficiale dell'organizzazione", max_length=100, verbose_name='Nome Organizzazione'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_postal_code',
            field=models.CharField(default='15073', max_length=10, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_region',
            field=models.CharField(default='Piemonte', max_length=100, verbose_name='Regione'),
        ),
    ]
