# Generated by Django 5.2.10 on 2026-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_add_site_settings_organization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='organization_email',
            field=models.EmailField(blank=True, default='mccastellazzob@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_phone',
            field=models.CharField(blank=True, default='+39 335 789 9368', max_length=30, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_street_address',
            field=models.CharField(blank=True, default='Via Camillo Benso Conte di Cavour, 28', help_text='Indirizzo della sede', max_length=200, verbose_name='Indirizzo'),
        ),
    ]
