# Generated by Django 5.2.10 on 2026-01-14 23:36

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0008_add_contact_fields_to_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='organization_street_address',
            field=models.CharField(blank=True, default="Via San Francesco d'Assisi, 1", help_text='Indirizzo della sede', max_length=200, verbose_name='Indirizzo'),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Nome identificativo del footer.', max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Solo il footer attivo verrà mostrato.', verbose_name='Attivo')),
                ('tagline', models.CharField(blank=True, help_text='Breve descrizione sotto il logo.', max_length=500, verbose_name='Tagline')),
                ('columns', wagtail.fields.StreamField([('column', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo colonna', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default')], 'label': 'Template', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Custom CSS Class', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Custom ID', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Tracking Event Category', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Tracking Event Label', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('custom_template', 1), ('custom_css_class', 2), ('custom_id', 3), ('ga_tracking_event_category', 4), ('ga_tracking_event_label', 5)]], {}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page link', 'required': False}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document link', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Other link', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es: fas fa-home', 'label': 'Icona FontAwesome', 'max_length': 50, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('settings', 6), ('page_link', 7), ('doc_link', 8), ('other_link', 9), ('button_title', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Link'}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 13)]], {})}, verbose_name='Colonne link')),
                ('social_links', wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp')], 'label': 'Piattaforma'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})}, verbose_name='Link social')),
                ('copyright_text', models.CharField(blank=True, help_text='Es: © 2026 MC Castellazzo. Tutti i diritti riservati.', max_length=255, verbose_name='Testo copyright')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text="Nome identificativo della navbar (es. 'Main Navigation').", max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Solo la navbar attiva verrà mostrata.', verbose_name='Attiva')),
                ('menu_items', wagtail.fields.StreamField([('link', 11), ('dropdown', 15)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default')], 'label': 'Template', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Custom CSS Class', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Custom ID', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Tracking Event Category', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Tracking Event Label', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('custom_template', 0), ('custom_css_class', 1), ('custom_id', 2), ('ga_tracking_event_category', 3), ('ga_tracking_event_label', 4)]], {}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page link', 'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document link', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Other link', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es: fas fa-home', 'label': 'Icona FontAwesome', 'max_length': 50, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('settings', 5), ('page_link', 6), ('doc_link', 7), ('other_link', 8), ('button_title', 9), ('icon', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo dropdown', 'max_length': 255}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es: fas fa-info-circle', 'label': 'Icona FontAwesome', 'max_length': 50, 'required': False}), 14: ('wagtail.blocks.ListBlock', (11,), {'label': 'Link nel dropdown'}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('icon', 13), ('links', 14)]], {})}, verbose_name='Voci di menu')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
