# Generated by Django 5.2.10 on 2026-01-15 00:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0009_add_navbar_footer_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='columns',
            field=models.CharField(choices=[('2', '2 colonne'), ('3', '3 colonne'), ('4', '4 colonne')], default='4', max_length=20, verbose_name='Colonne'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='show_filters',
            field=models.BooleanField(default=True, verbose_name='Mostra filtri categoria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo galleria', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostra filtri categoria', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Didascalia', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('all', 'Tutti'), ('raduni', 'Raduni'), ('escursioni', 'Escursioni'), ('gare', 'Gare'), ('sociali', 'Eventi Sociali')], 'label': 'Categoria'}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('category', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Immagini'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-2', '2 colonne'), ('grid-cols-3', '3 colonne'), ('grid-cols-4', '4 colonne')], 'label': 'Colonne'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_filters', 1), ('images', 6), ('columns', 7)]], {})}, help_text='Opzionale: usa i blocchi o le immagini sotto', verbose_name='Gallerie (blocchi)'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Didascalia')),
                ('category', models.CharField(choices=[('all', 'Tutti'), ('raduni', 'Raduni'), ('escursioni', 'Escursioni'), ('gare', 'Gare'), ('sociali', 'Eventi Sociali')], default='all', max_length=50, verbose_name='Categoria')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Immagine')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.gallerypage')),
            ],
            options={
                'verbose_name': 'Immagine Galleria',
                'verbose_name_plural': 'Immagini Galleria',
                'ordering': ['sort_order'],
            },
        ),
    ]
