# Generated by Django 5.2.10 on 2026-01-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_gallerypage_columns_gallerypage_show_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_event',
            field=models.ForeignKey(blank=True, help_text='Evento da mostrare nella homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.eventdetailpage', verbose_name='Evento in evidenza'),
        ),
    ]
