# Generated by Django 5.2.10 on 2026-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_add_featured_event_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_badge',
            field=models.CharField(blank=True, help_text='Es: IL PIÙ ANTICO MOTO CLUB DEL PIEMONTE', max_length=100, verbose_name='Badge hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Es: di passione, adrenalina e fratellanza su due ruote', max_length=500, verbose_name='Tagline hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Es: Castellazzo Bormida (parte evidenziata in oro)', max_length=255, verbose_name='Sottotitolo hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Es: Moto Club', max_length=255, verbose_name='Titolo hero'),
        ),
    ]
