# Generated by Django 5.2.10 on 2026-01-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0044_layoutsettings_recaptcha_public_key_and_more'),
        ('website', '0012_add_hero_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_carousel',
            field=models.ForeignKey(blank=True, help_text='Seleziona un Carousel da Snippets > Carousel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coderedcms.carousel', verbose_name='Slider fotografico'),
        ),
    ]
