# Generated by Django 5.2.10 on 2026-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_hero_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_subtitle',
            field=models.CharField(blank=True, help_text='Es: Diventa parte della famiglia del Moto Club più antico del Piemonte', max_length=500, verbose_name='Sottotitolo CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, help_text='Es: Unisciti a Noi', max_length=255, verbose_name='Titolo CTA'),
        ),
    ]
