# Generated by Django 5.2.10 on 2026-01-16 23:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0014_add_cta_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='founding_date',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_alternate_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_city',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_country',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_founding_year',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_postal_code',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_region',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='organization_street_address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Breve descrizione del motoclub per la homepage', verbose_name='Descrizione breve'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL pagina Facebook', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Icona per browser tab (32x32px consigliato)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© MC Castellazzo Bormida - Tutti i diritti riservati', help_text='Copyright o altro testo per il footer', max_length=255, verbose_name='Testo Footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL profilo Instagram', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo per header e navbar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL canale YouTube', verbose_name='YouTube URL'),
        ),
    ]
