# Generated by Django 5.2.10 on 2026-01-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_fix_sitesettings_site_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founding_year',
            field=models.PositiveIntegerField(default=1933, help_text='Anno di fondazione del motoclub (es. 1933)', verbose_name='Anno di fondazione'),
        ),
    ]
