# Generated by Django 5.2.10 on 2026-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_add_founding_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='member_of_name',
            field=models.CharField(blank=True, default='FMI - Federazione Motociclistica Italiana', help_text='Nome della federazione sportiva di appartenenza', max_length=200, verbose_name='Federazione di appartenenza'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sport',
            field=models.CharField(default='Motorcycling', help_text='Tipo di sport praticato (es. Motorcycling)', max_length=100, verbose_name='Sport'),
        ),
    ]
