# Generated by Django 5.2.10 on 2026-01-17 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0017_add_sport_and_member_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text="Nome della categoria (es. 'Raduni', 'Escursioni')", max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text="Identificatore URL-friendly (es. 'raduni', 'escursioni')", max_length=100, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='fas fa-images', help_text="Classe FontAwesome (es. 'fas fa-users', 'fas fa-mountain')", max_length=50, verbose_name='Icona FontAwesome')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione nei filtri', verbose_name='Ordine')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Categoria Galleria',
                'verbose_name_plural': 'Categorie Galleria',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
