# Generated by Django 5.2.10 on 2026-01-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0019_update_gallery_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='Categoria da applicare alle immagini importate dalla collezione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.gallerycategory', verbose_name='Categoria predefinita'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='source_collection',
            field=models.ForeignKey(blank=True, help_text="Importa automaticamente tutte le immagini da questa collezione. Il titolo dell'immagine viene usato come titolo, i tag come descrizione.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection', verbose_name='Collezione sorgente'),
        ),
    ]
