# Generated by Django 5.2.10 on 2026-01-17 14:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_add_gallery_source_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='default_category',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='source_collection',
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery', 9), ('collection_gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo galleria', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostra filtri categoria', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo dell'immagine (visibile nel lightbox)", 'label': 'Titolo', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Descrizione dell'immagine (visibile nel lightbox)", 'label': 'Descrizione', 'max_length': 500, 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('website.GalleryCategory',), {'help_text': 'Categoria per il filtro galleria', 'label': 'Categoria', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('caption', 4), ('category', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Immagini'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-2', '2 colonne'), ('grid-cols-3', '3 colonne'), ('grid-cols-4', '4 colonne')], 'label': 'Colonne'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_filters', 1), ('images', 7), ('columns', 8)]], {}), 10: ('apps.website.blocks.CollectionChooserBlock', (), {'help_text': "Importa tutte le immagini da questa collezione. Il titolo dell'immagine viene usato come titolo, i tag come descrizione.", 'label': 'Collezione'}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('website.GalleryCategory',), {'help_text': 'Categoria da applicare a tutte le immagini della collezione.', 'label': 'Categoria', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('collection', 10), ('category', 11)]], {})}, help_text='Usa blocchi immagine singola o importa da collezioni Wagtail', verbose_name='Gallerie (blocchi)'),
        ),
    ]
