# Generated by Django 5.2.10 on 2026-01-17 19:45

import apps.website.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_source_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='faq',
            field=wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'La domanda frequente', 'label': 'Domanda', 'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'La risposta alla domanda', 'label': 'Risposta'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, help_text='Aggiungi le FAQ. Lascia vuoto per nascondere la sezione.', verbose_name='Domande Frequenti'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='faq_subtitle',
            field=models.CharField(blank=True, default='Trova rapidamente le risposte alle domande più comuni', max_length=255, verbose_name='Sottotitolo FAQ'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='faq_title',
            field=models.CharField(blank=True, default='Domande Frequenti', max_length=100, verbose_name='Titolo sezione FAQ'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery',
            field=wagtail.fields.StreamField([('gallery', 9), ('collection_gallery', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo galleria', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostra filtri categoria', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo dell'immagine (visibile nel lightbox)", 'label': 'Titolo', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Descrizione dell'immagine (visibile nel lightbox)", 'label': 'Descrizione', 'max_length': 500, 'required': False}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('website.GalleryCategory',), {'help_text': 'Categoria per il filtro galleria', 'label': 'Categoria', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('caption', 4), ('category', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Immagini'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid-cols-2', '2 colonne'), ('grid-cols-3', '3 colonne'), ('grid-cols-4', '4 colonne')], 'label': 'Colonne'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_filters', 1), ('images', 7), ('columns', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo visualizzato sopra la galleria (es. 'Raduno 2024')", 'label': 'Titolo sezione', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': apps.website.blocks.get_collection_choices, 'help_text': "Importa tutte le immagini da questa collezione. Il titolo dell'immagine viene usato come titolo, i tag come descrizione.", 'label': 'Collezione'}), 12: ('wagtail.snippets.blocks.SnippetChooserBlock', ('website.GalleryCategory',), {'help_text': 'Categoria da applicare a tutte le immagini della collezione.', 'label': 'Categoria', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('collection', 11), ('category', 12)]], {})}, help_text='Usa blocchi immagine singola o importa da collezioni Wagtail', verbose_name='Gallerie (blocchi)'),
        ),
    ]
