# Generated by Django 5.2.10 on 2026-01-17 22:29

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0022_add_faq_to_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Nome identificativo del carousel.', max_length=255, verbose_name='Nome')),
                ('show_controls', models.BooleanField(default=True, help_text='Mostra frecce di navigazione.', verbose_name='Mostra controlli')),
                ('show_indicators', models.BooleanField(default=True, help_text='Mostra pallini indicatori sotto il carousel.', verbose_name='Mostra indicatori')),
                ('autoplay', models.BooleanField(default=True, help_text='Cambia slide automaticamente.', verbose_name='Autoplay')),
                ('interval', models.PositiveIntegerField(default=5000, help_text='Tempo tra le slide in millisecondi.', verbose_name='Intervallo (ms)')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Carousel Semplice',
                'verbose_name_plural': 'Carousel Semplici',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='SimpleCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text="Titolo sovrapposto all'immagine.", max_length=255, verbose_name='Titolo')),
                ('subtitle', models.CharField(blank=True, help_text='Testo descrittivo sotto il titolo.', max_length=500, verbose_name='Sottotitolo')),
                ('button_text', models.CharField(blank=True, help_text='Testo del pulsante CTA (lascia vuoto per nascondere).', max_length=100, verbose_name='Testo pulsante')),
                ('button_url', models.CharField(blank=True, help_text='Link del pulsante (può essere URL esterno o percorso interno).', max_length=500, verbose_name='URL pulsante')),
                ('overlay_opacity', models.PositiveIntegerField(default=40, help_text="Opacità dell'overlay scuro (0-100).", verbose_name='Opacità overlay')),
                ('carousel', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='website.simplecarousel')),
                ('image', models.ForeignKey(help_text='Immagine di sfondo della slide (consigliato: 1920x800).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
                'ordering': ['sort_order'],
            },
        ),
    ]
