# Generated by Django 5.2.10 on 2026-01-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0044_layoutsettings_recaptcha_public_key_and_more'),
        ('website', '0023_simple_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='simple_carousel',
            field=models.ForeignKey(blank=True, help_text='Carousel semplice senza bug - CONSIGLIATO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.simplecarousel', verbose_name='Simple Carousel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_carousel',
            field=models.ForeignKey(blank=True, help_text='Carousel CodeRedCMS - può avere bug, usa Simple Carousel se non funziona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coderedcms.carousel', verbose_name='Slider fotografico (CodeRedCMS)'),
        ),
    ]
