# Generated by Django 5.2.10 on 2026-01-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-images', help_text="Classe FontAwesome, es: 'fas fa-users', 'fas fa-mountain'", max_length=50, verbose_name='Icona FontAwesome'),
        ),
    ]
