# Generated by Django 5.2.13 on 2026-05-02 22:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_gallerycategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='attachments',
            field=wagtail.fields.StreamField([('attachment', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo', 'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Documento'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Descrizione', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('description', 2)]], {})}, verbose_name='Allegati'),
        ),
        migrations.AlterField(
            model_name='boardpage',
            name='members',
            field=wagtail.fields.StreamField([('member', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nome', 'max_length': 255, 'translatable': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Ruolo', 'max_length': 100}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Biografia', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('image', 2), ('bio', 3)]], {})}, verbose_name='Membri'),
        ),
    ]
